### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by JohnTao** [pidiscovery/pi#1]
![Uploading TIM图片20171212001516.png…]()

**Comment by JohnTao** [comment]
![Uploading TIM图片20171212001516.png…]()

**Comment by JohnTao** [comment]
![aaaa](https://user-images.githubusercontent.com/1073365/33841127-ca2fe72a-ded1-11e7-949d-08db116d56fd.png)

**Comment by wallex64** [comment]
Run this command before run cmake

```bash
git submodule update --init --recursive
```
